package repackage.net.sf.persist.tests.common;

import java.util.Objects;

public class Simple {

  private long id;
  private String stringCol;
  private long longCol;

  public Simple() {}

  public Simple(long longCol, String stringCol) {
    this.longCol = longCol;
    this.stringCol = stringCol;
  }

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getStringCol() {
    return stringCol;
  }

  public void setStringCol(String stringCol) {
    this.stringCol = stringCol;
  }

  public long getLongCol() {
    return longCol;
  }

  public void setLongCol(long intCol) {
    this.longCol = intCol;
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, longCol, stringCol);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;

    final Simple other = (Simple) obj;

    // do not compare ids -- will be tested in the autogeneratedkeys tests
    // if (id != other.id) return false;

    if (longCol != other.longCol) return false;
    if (stringCol == null) {
      if (other.stringCol != null) return false;
    } else if (!stringCol.equals(other.stringCol)) return false;

    return true;
  }

  @Override
  public String toString() {
    return "id=" + id + " longCol=" + longCol + " stringCol=" + stringCol;
  }
}
