package org.nkjmlab.sorm4j.config;

import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.List;
import org.nkjmlab.sorm4j.mapping.Column;
import org.nkjmlab.sorm4j.mapping.ColumnToAccessorMap;


public interface ColumnFieldMapper extends OrmConfig {

  List<Column> getAutoGeneratedColumns(DatabaseMetaData metaData, String tableName)
      throws SQLException;

  List<Column> getColumns(DatabaseMetaData metaData, String tableName) throws SQLException;

  List<String> getPrimaryKeys(DatabaseMetaData metaData, String tableName) throws SQLException;

  ColumnToAccessorMap createColumnToAccessorMap(Class<?> objectClass, List<Column> columns);

  ColumnToAccessorMap createColumnToAccessorMap(Class<?> objectClass);



}
