package org.nkjmlab.sorm4j.internal.context.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.nkjmlab.sorm4j.internal.context.PreparedStatementSupplier;

public final class DefaultPreparedStatementSupplier implements PreparedStatementSupplier {

  public DefaultPreparedStatementSupplier() {}

  @Override
  public PreparedStatement prepareStatement(
      Connection connection, String sql, String[] autoGeneratedColumnsArray) throws SQLException {
    return connection.prepareStatement(sql, autoGeneratedColumnsArray);
  }

  @Override
  public PreparedStatement prepareStatement(Connection connection, String sql) throws SQLException {
    return connection.prepareStatement(sql);
  }
}
