package org.nkjmlab.sorm4j.mapping;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public interface PreparedStatementSupplier {


  PreparedStatement prepareStatement(Connection connection, String sql) throws SQLException;

  PreparedStatement prepareStatement(Connection connection, String sql,
      String[] autoGeneratedColumnsArray) throws SQLException;

}
