package org.nkjmlab.sorm4j.util;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public final class PreparedStatementUtils {

  private PreparedStatementUtils() {}

  public static PreparedStatement getPreparedStatement(Connection connection, String sql)
      throws SQLException {
    return connection.prepareStatement(sql);
  }

  public static PreparedStatement getPreparedStatementWithAutoGeneratedKeys(Connection connection,
      String sql, String[] autoGeneratedKeys) throws SQLException {
    return (autoGeneratedKeys == null || autoGeneratedKeys.length == 0)
        ? connection.prepareStatement(sql)
        : connection.prepareStatement(sql, autoGeneratedKeys);
  }


}
